### PR TITLE
Migrate to Now V2

### PR DESCRIPTION
**Pull request by robwebdev**
- [x] Create a serverless endpoint for sitemap.xml
   - [x] Add `src/sitemap.js` or similar
   - [ ] Register the [function](https://vercel.com/docs/configuration#project/functions) in now.json
   - [ ] Add a [route](https://vercel.com/docs/configuration#project/routes) to now.json pointing `sitemap.xml` to the file created above
   - [x] Port over the `sitemapAndRobots.js` code to the new endpoint
- [ ] Audit the rest of the custom `server.js` and add TODO's to this list for things that need attention. Bablic for example.
- [x] Update deployment commands

### CODE REVIEW

**Comment by yoavaviram** [comment]
Hi @robwebdev, can you please give us an update as to where this PR stands? How close are we to finishing this? Anything I can do to help?

**Comment by robwebdev** [comment]
@yoavaviram I've updated the description of the PR with a todo list. I won't be able to pick any of that up at least until the weekend so feel free to grab any tasks in the meantime.

**Comment by yoavaviram** [comment]
Thanks for the update. If you can get sitemaps sorted then we can deploy and fix bablic after.

**Comment by robwebdev** [comment]
@yoavaviram I've added endpoints for sitemap.xml and robots.txt. The CI build is failing at the moment and I ran out of time trying to fix it, but should be ok to merge and deploy this after a manual test if necessary. In that case I'll follow up with another PR to fix CI.

You can test here: https://opt-out-eu-robwebdev.your-digital-rights.now.sh/

**Comment by yoavaviram** [comment]
Thanks @robwebdev! I've merged this PR. This way you can submit a follow up PR as you've suggested.

**Comment by yoavaviram** [comment]
Hi @robwebdev , do you think you'll have time to work on the tests? Also, I'm not sure if this version using server.js or not.

**Pull request merged**
